-- ============================================================
-- BoMRA Schema Patch
-- Run this AFTER the original schema.sql
-- Adds missing tables and fixes column issues
-- ============================================================

USE bomra_system;

-- ─── 1. INSPECTORS profile table ─────────────────────────────────────────────
-- inspections table references users(user_id) for inspector_id but there is
-- no inspectors profile table. Add one so inspectors have contact details.
CREATE TABLE IF NOT EXISTS inspectors (
    inspector_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id      INT          NOT NULL UNIQUE,
    name         VARCHAR(150) NOT NULL,
    contact      VARCHAR(100),
    region       VARCHAR(100),
    created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Auto-populate inspectors table from existing inspector users
INSERT IGNORE INTO inspectors (user_id, name)
SELECT user_id, name FROM users WHERE role = 'inspector';

-- ─── 2. MEDICINE REGISTRATION STATUS on the batch ────────────────────────────
-- medicine_batches has no column to mark whether a batch is approved for
-- distribution. The applications table tracks the decision, but queries that
-- need "give me approved batches" must join applications. Add a denormalised
-- status column on medicine_batches so delivery queries stay simple.
ALTER TABLE medicine_batches
    ADD COLUMN IF NOT EXISTS approval_status
        ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending'
        AFTER expiry_date;

-- Sync existing data: mark batches whose application is approved/rejected
UPDATE medicine_batches mb
JOIN (
    SELECT batch_id, status
    FROM applications
    WHERE (batch_id, application_id) IN (
        SELECT batch_id, MAX(application_id)
        FROM applications
        GROUP BY batch_id
    )
) latest_app ON latest_app.batch_id = mb.batch_id
SET mb.approval_status = latest_app.status;

-- ─── 3. REVIEW_NOTES column on applications ───────────────────────────────────
-- review_application.php writes review_notes but some older schema versions
-- omit it. This is safe to run even if it already exists (IF NOT EXISTS guard).
ALTER TABLE applications
    ADD COLUMN IF NOT EXISTS review_notes TEXT AFTER status;

-- ─── 4. SUBMITTED_AT alias — add index for faster pending lookups ─────────────
CREATE INDEX IF NOT EXISTS idx_applications_status
    ON applications (status);

-- ─── 5. DELIVERY ITEMS must reference approved batches ───────────────────────
-- No schema change needed — enforcement is in PHP.
-- But add an index so "find approved batches for supplier X" is fast.
CREATE INDEX IF NOT EXISTS idx_batches_supplier_status
    ON medicine_batches (supplier_id, approval_status);

-- ─── 6. STOCK index for fast facility lookups ────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_stock_facility
    ON stock (facility_id);

-- ─── 7. TRIGGER: sync approval_status when an application is reviewed ─────────
-- Drop first in case it exists from a previous run
DROP TRIGGER IF EXISTS trg_sync_batch_approval;

DELIMITER $$
CREATE TRIGGER trg_sync_batch_approval
AFTER UPDATE ON applications
FOR EACH ROW
BEGIN
    IF NEW.status IN ('approved', 'rejected') AND OLD.status = 'pending' THEN
        UPDATE medicine_batches
        SET approval_status = NEW.status
        WHERE batch_id = NEW.batch_id;
    END IF;
END$$
DELIMITER ;

-- ─── 8. TRIGGER: auto-create inspector profile on registration ───────────────
DROP TRIGGER IF EXISTS trg_inspector_profile;

DELIMITER $$
CREATE TRIGGER trg_inspector_profile
AFTER INSERT ON users
FOR EACH ROW
BEGIN
    IF NEW.role = 'inspector' THEN
        INSERT IGNORE INTO inspectors (user_id, name) VALUES (NEW.user_id, NEW.name);
    END IF;
END$$
DELIMITER ;

-- ─── Verification queries (run to confirm patch applied) ─────────────────────
-- SELECT COUNT(*) AS inspectors_count  FROM inspectors;
-- SELECT COUNT(*) AS approved_batches  FROM medicine_batches WHERE approval_status = 'approved';
-- SHOW COLUMNS FROM medicine_batches LIKE 'approval_status';
-- SHOW TRIGGERS LIKE 'trg_%';

-- ─── 9. PASSWORD RESET TOKENS ─────────────────────────────────────────────────
-- Stores hashed temporary codes generated by forgot_password.php.
-- One active token per user at a time. Expired tokens are cleaned on next request.
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    token_id   INT AUTO_INCREMENT PRIMARY KEY,
    user_id    INT          NOT NULL UNIQUE,
    token_hash VARCHAR(255) NOT NULL,
    expires_at DATETIME     NOT NULL,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reset_tokens_expiry
    ON password_reset_tokens (user_id, expires_at);
